### ISSUE TITLE
i get this error NULL

### ISSUE THREAD

**Issue by bowdyyy** [Mitsugaru/PlayerPoints#29]
31.01 18:54:47 [Server] ERROR null
31.01 18:54:47 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'souls' in plugin PlayerPoints v2.1.5-SNAPSHOT - plugin is disabled.
31.01 18:54:47 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[patched_1.13.2.jar:git-Paper-488]
31.01 18:54:47 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-488]
31.01 18:54:47 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-488]
31.01 18:54:47 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1792) ~[patched_1.13.2.jar:git-Paper-488]
31.01 18:54:47 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1595) ~[patched_1.13.2.jar:git-Paper-488]
31.01 18:54:47 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-488]
31.01 18:54:47 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-488]
31.01 18:54:47 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-488]
31.01 18:54:47 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
31.01 18:54:47 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
31.01 18:54:47 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-488]
31.01 18:54:47 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-488]
31.01 18:54:47 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-488]
31.01 18:54:47 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-488]
31.01 18:54:47 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-488]

**Comment by madtomic** [comment]
What other plugin are you using that is trying to run command “souls”?
